# Generated by Django 5.2.4 on 2025-12-26 17:25

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userproduct",
            name="detected_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=App.models.UniqueUploadPath("user_products/detected"),
            ),
        ),
        migrations.AlterField(
            model_name="userproduct",
            name="original_image",
            field=models.ImageField(
                upload_to=App.models.UniqueUploadPath("user_products/original")
            ),
        ),
    ]
